FROM python:3.11

ENV PYTHONUNBUFFERED True

WORKDIR /app
COPY app/ ./app
COPY requirements.txt .

RUN apt-get update && apt-get install -y gcc libpq-dev
RUN pip install --upgrade pip
RUN pip install -r requirements.txt 

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]