[project]
name = "financial-data-scrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyaml>=25.1.0",
    "pytest>=8.3.5",
    "selenium>=4.32.0",
]
