steps:
  # Atualiza pip e instala dependências
  - name: python:3.12-slim           # imagem pública do Docker Hub
    entrypoint: bash
    args:
      - -c
      - |
          set -e
          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            curl

          pip install --upgrade pip
          pip install -r requirements.txt

          curl -sSLo constraints.txt https://raw.githubusercontent.com/apache/airflow/main/constraints-3.12.txt
          pip install "apache-airflow" --constraint constraints.txt

          pip install -e .
          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
