steps:
  - id: running tests
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -c
      - |
          set -e

          # Instala dependências do sistema
          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            curl \
            gnupg \
            ca-certificates \
            python3-pip

          # Verifica gcloud e projeto
          gcloud --version
          gcloud config set project $PROJECT_ID

          # Atualiza pip e instala dependências
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "apache-airflow==2.9.0" \
            --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.12.txt"
          pip install -e .

          # Gera identity token para Cloud Run
          ID_TOKEN=$(gcloud auth print-identity-token)
          curl -H "Authorization: Bearer $ID_TOKEN" -fs $_SELENIUM_URL/status || exit 1

          # Exporta variáveis usadas nos testes
          export SELENIUM_URL=$_SELENIUM_URL

          # Executa os testes
          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
