steps:
  # Atualiza pip e instala dependências
  - name: python:3.13-slim           # imagem pública do Docker Hub
    entrypoint: bash
    args:
      - -c
      - |
          set -e
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
