steps:
  # Atualiza pip e instala dependências
  - id: running tests
    name: python:3.12-slim           # imagem pública do Docker Hub
    entrypoint: bash
    args:
      - -c
      - |
          set -e
          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            curl

          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "apache-airflow==2.9.0" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.12.txt"
          pip install -e .

          export SELENIUM_REMOTE_URL=https://selenium-chrome-standalone-212994923775.us-central1.run.app/wd/hub
          curl -fs $SELENIUM_REMOTE_URL/status || exit 1

          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
