steps:
  # Atualiza pip e instala dependências
  - name: python:3.13-slim           # imagem pública do Docker Hub
    entrypoint: bash
    args:
      - -c
      - |
          set -e
          apt-get update && apt-get install -y --no-install-recommends build-essential
          pip install --upgrade pip
          pip install -r requirements.txt
          AIRFLOW_VERSION=2.9.0
          PYTHON_VERSION=3.13
          pip install "apache-airflow==${AIRFLOW_VERSION}" \
            --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${AIRFLOW_VERSION}/constraints-${PYTHON_VERSION}.txt"
          pip install -e .
          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
