steps:
  - id: running tests
    name: python:3.12-slim
    entrypoint: bash
    args:
      - -c
      - |
          set -e

          apt-get update && apt-get install -y --no-install-recommends \
            build-essential \
            curl \
            gnupg \
            ca-certificates

          # Instala gcloud CLI para gerar identity token
          curl -sSL https://sdk.cloud.google.com | bash
          export PATH=$PATH:/root/google-cloud-sdk/bin

          # Autentica (Cloud Build já está autenticado, basta ativar o SDK)
          gcloud config set project $PROJECT_ID

          # Instala dependências do Python
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "apache-airflow==2.9.0" \
            --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.0/constraints-3.12.txt"
          pip install -e .

          # Gera token para autenticar contra Cloud Run
          ID_TOKEN=$(gcloud auth print-identity-token)

          # Testa se o Selenium está pronto
          curl -H "Authorization: Bearer $ID_TOKEN" \
               -fs https://selenium-chrome-standalone-212994923775.us-central1.run.app/wd/hub/status || exit 1

          # Exporta a URL (sem token) — o token será usado no seu código Python
          export SELENIUM_URL=https://selenium-chrome-standalone-212994923775.us-central1.run.app/wd/hub

          # Executa os testes
          pytest tests -q

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
