project_id: estud-460321

env: C:/Users/htorr/Documents/vscode/meus_projetos/financial_data_scrapper/.env

urls:
  commodity: https://br.investing.com/indices/bloomberg-commodity-historical-data
  usd_currency: https://br.investing.com/currencies/usd-cny-historical-data
  chinese_pmi: https://sbcharts.investing.com/charts_xml/cce9bf7363d8e7d1609664b9b9e2d468_max.json

services:
  bigquery:
    dataset: financial_data_scrapper_bronze
  
  requests:
    headers: {
      "Origin": "https://br.investing.com",
      "Referer": "https://br.investing.com/",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Safari/537.36",
      "X-Write-Key": "fj23xkcWDdlAzhDYRN4ReiCn30Cdqu0N:H92VagPxy3OLBZcWCvZgkAzlts1C0jOm"
    }
      
