urls:
  commodity: https://br.investing.com/indices/bloomberg-commodity-chart
  currencies: https://br.investing.com/currencies/usd-cny-historical-data
  chinese_cash_services: https://br.investing.com/economic-calendar/chinese-caixin-services-pmi-596
